// Author: Claude (Anthropic) — this file is AI generated, see ../../../docs/init.md.

import type { JSX } from "react";
import { Link } from "react-router";

import { useCatalogueState } from "../catalogue";
import { fmt } from "../format";
import { usePageTitle } from "../title";

const REPO = "https://github.com/mborne/gpf-catalogue";

/**
 * What the banner on every other page says in one line.
 *
 * The warning has to be read once, not read six lines deep on every route, so
 * the detail lives here and the banner is a link to it. A page has room the
 * banner did not: who published the site, what generated it, how the figures
 * are produced and where the authoritative catalogue is.
 *
 * It reads the catalogue if it happens to be loaded, but renders without it —
 * this is the page to reach when the data fails to load.
 */
export function AboutPage(): JSX.Element {
  const { data } = useCatalogueState();
  usePageTitle("About");

  return (
    <>
      <p className="lead">
        <strong>This is not an official Géoplateforme or IGN site.</strong> It is a
        personal experiment, published by an individual and not endorsed by either.
        Nothing here speaks for the Géoplateforme, and nothing here should be quoted as
        if it did.
      </p>

      <section className="card">
        <h2>Where the authoritative catalogue is</h2>
        <p className="prose-p">
          The Géoplateforme publishes its catalogue at{" "}
          <a
            href="https://cartes.gouv.fr/rechercher-une-donnee/"
            rel="noopener noreferrer"
            target="_blank"
          >
            cartes.gouv.fr
          </a>
          , over the CSW service <code>{data?.stats.source ?? "data.geopf.fr/csw"}</code>
          . That service is the source of truth. This site is a copy of it, and a copy
          is wrong as soon as the original moves.
        </p>
      </section>

      <section className="card">
        <h2>How the figures are built</h2>
        <p className="prose-p">
          A pipeline mirrors the catalogue record by record, converts each ISO 19115-3
          document into a small pivot model, and aggregates the result into two JSON
          documents that this page reads —{" "}
          <code>catalogue.json</code> and <code>stats.json</code>, sitting next to it.
          Filtering happens in your browser, over those documents; nothing you type is
          sent anywhere.
        </p>
        <p className="prose-p">
          The mirror is rebuilt <strong>once a week</strong>, so every figure on this
          site lags behind the live service by up to seven days
          {data ? ` — ${fmt(data.stats.count)} resources at the last rebuild` : ""}. A
          record published, corrected or withdrawn since then is not reflected here.
        </p>
        <p className="prose-p">
          The conversion is lossy by design, and a few records never make it through at
          all. What is missing, and why, is measured rather than estimated: see{" "}
          <Link to="/quality">Quality</Link>.
        </p>
      </section>

      <section className="card">
        <h2>Generated by Claude</h2>
        <p className="prose-p">
          Almost everything here — the pipeline, this page and its wording — was
          generated by{" "}
          <a href="https://claude.ai" rel="noopener noreferrer" target="_blank">
            Claude
          </a>
          , Anthropic's assistant, under review. Every generated file says so in a
          line of its own, and the repository records how it was done.
        </p>
      </section>

      <section className="card">
        <h2>Source code</h2>
        <p className="prose-p">
          Everything behind this site is public — the harvester, the parser, the pivot
          model, this page, and the whole history of the three:{" "}
          <a href={`${REPO}#readme`} rel="noopener noreferrer" target="_blank">
            github.com/mborne/gpf-catalogue
          </a>
          . The two documents it publishes,{" "}
          <code>catalogue.json</code> and <code>stats.json</code>, can be downloaded
          without cloning anything.
        </p>
        <ul className="prose">
          <li>
            <a
              href={`${REPO}/blob/main/docs/why.md`}
              rel="noopener noreferrer"
              target="_blank"
            >
              <code>docs/why.md</code>
            </a>{" "}
            — the measurements that justify the pivot model: what a full ISO record
            weighs, what the CSW service does and does not answer.
          </li>
          <li>
            <a
              href={`${REPO}/blob/main/docs/model.md`}
              rel="noopener noreferrer"
              target="_blank"
            >
              <code>docs/model.md</code>
            </a>{" "}
            — every field of the pivot model, where it is read in the ISO document, and
            how often the catalogue fills it.
          </li>
          <li>
            <a
              href={`${REPO}/blob/main/docs/overview.md`}
              rel="noopener noreferrer"
              target="_blank"
            >
              <code>docs/overview.md</code>
            </a>{" "}
            — this site: its routes, and the rules behind the publisher, licence family
            and year shown on the charts.
          </li>
          <li>
            <a
              href={`${REPO}/blob/main/docs/init.md`}
              rel="noopener noreferrer"
              target="_blank"
            >
              <code>docs/init.md</code>
            </a>{" "}
            — how the repository was generated, and what was asked for.
          </li>
          <li>
            <a
              href={`${REPO}/blob/main/ROADMAP.md`}
              rel="noopener noreferrer"
              target="_blank"
            >
              <code>ROADMAP.md</code>
            </a>{" "}
            — what is done, what is next, and the known issues left open.
          </li>
        </ul>
      </section>

      <section className="card">
        <h2>Publication</h2>
        <p className="prose-p">
          <a
            href="https://mborne.github.io/mentions-legales/"
            rel="noopener noreferrer"
            target="_blank"
          >
            Mentions légales
          </a>
        </p>
      </section>
    </>
  );
}
