// Author: Claude (Anthropic) — this file is AI generated, see ../../../docs/init.md.

import type { JSX } from "react";
import { NavLink, Outlet } from "react-router";

import { useCatalogueState } from "../catalogue";
import { fmt } from "../format";
import { toggleTheme } from "../theme";

/** The three sections, in the order they answer questions about the catalogue. */
const TABS = [
  { to: "/overview", label: "Overview" },
  { to: "/records", label: "Records" },
  { to: "/quality", label: "Quality" },
];

/* Ahead of every figure on the site, because a catalogue overview published by an
   individual is easy to mistake for the catalogue's own. It sits in the layout
   rather than on each page, so no route can be reached without it.

   The sentence that carries the warning is the `<summary>`, so it is on screen on
   every route whatever the state of the `<details>`; what folds away is only the
   detail of who built it and how stale the figures are, which has to be readable
   once and not on every page load. */
function Disclaimer(): JSX.Element {
  return (
    <details className="disclaimer">
      <summary>
        <strong>This is not an official Géoplateforme or IGN site.</strong>
      </summary>
      <p>
        It is a personal experiment, published by an individual and not endorsed by
        either. Almost everything here — the code, this page and its wording — was
        generated by{" "}
        <a href="https://claude.ai" rel="noopener noreferrer" target="_blank">
          Claude
        </a>
        . The figures are computed from a copy of the public CSW catalogue rebuilt once
        a week, so they lag behind it and may be wrong; the authoritative source is{" "}
        <a
          href="https://cartes.gouv.fr/rechercher-une-donnee/"
          rel="noopener noreferrer"
          target="_blank"
        >
          cartes.gouv.fr
        </a>
        .
      </p>
      <a
        className="disclaimer-legal"
        href="https://mborne.github.io/mentions-legales/"
        rel="noopener noreferrer"
        target="_blank"
      >
        Mentions légales
      </a>
    </details>
  );
}

export function Layout(): JSX.Element {
  const { data } = useCatalogueState();
  const source = data?.stats.source ?? "data.geopf.fr/csw";

  return (
    <>
      <header className="topbar">
        <div className="topbar-inner">
          <div>
            <h1>
              Géoplateforme catalogue <span className="tag-unofficial">unofficial</span>
            </h1>
            <p className="subtitle">
              {data
                ? `${fmt(data.stats.count)} resources harvested from ${data.stats.source}`
                : "Loading…"}
            </p>
          </div>
          <button
            type="button"
            className="ghost"
            aria-label="Switch colour theme"
            onClick={toggleTheme}
          >
            Theme
          </button>
        </div>
        {/* Real links, so a tab can be opened in a new window, bookmarked and shared —
            which three buttons toggling `hidden` could not be. */}
        <nav className="tabs">
          {TABS.map((tab) => (
            <NavLink
              key={tab.to}
              to={tab.to}
              className={({ isActive }) => (isActive ? "tab active" : "tab")}
            >
              {tab.label}
            </NavLink>
          ))}
        </nav>
      </header>

      <main>
        <Disclaimer />
        <Outlet />
      </main>

      <footer className="footer">
        <p>
          Unofficial. Built from <code>{source}</code> by{" "}
          <a
            href="https://github.com/mborne/gpf-catalogue"
            rel="noopener noreferrer"
            target="_blank"
          >
            gpf-catalogue
          </a>
          , an AI generated experiment. The site reads <code>catalogue.json</code> and{" "}
          <code>stats.json</code> next to it; nothing is sent anywhere.
        </p>
        <p>
          <a
            href="https://mborne.github.io/mentions-legales/"
            rel="noopener noreferrer"
            target="_blank"
          >
            Mentions légales
          </a>
        </p>
      </footer>
    </>
  );
}
